stages:
  - cypress-api-test-run

cypress-test-api-prod:
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  stage: cypress-api-test-run
  script: 
    - npm install cypress
    - npx cypress run --record --key e33e176a-84f8-4997-a7de-54e441ac751c